In [1]:
import pandas as pd


In [2]:
data = pd.read_csv('data.csv')
data.head()

ID  air_time1  disp_index1  gmrt_in_air1  gmrt_on_paper1  \
0  id_1       5160     0.000013    120.804174       86.853334   
1  id_2      51980     0.000016    115.318238       83.448681   
2  id_3       2600     0.000010    229.933997      172.761858   
3  id_4       2130     0.000010    369.403342      183.193104   
4  id_5       2310     0.000007    257.997131      111.275889   

   max_x_extension1  max_y_extension1  mean_acc_in_air1  mean_acc_on_paper1  \
0               957              6601          0.361800            0.217459   
1              1694              6998          0.272513            0.144880   
2              2333              5802          0.387020            0.181342   
3              1756              8159          0.556879            0.164502   
4               987              4732          0.266077            0.145104   

   mean_gmrt1  ...  mean_jerk_in_air25  mean_jerk_on_paper25  \
0  103.828754  ...            0.141434              0.024471   
1   99.383459  ...            0.049663              0.018368   
2  201.347928  ...            0.178194              0.017174   
3  276.298223  ...            0.113905              0.019860   
4  184.636510  ...            0.121782              0.020872   

   mean_speed_in_air25  mean_speed_on_paper25  num_of_pendown25  paper_time25  \
0             5.596487               3.184589                71         40120   
1             1.665973               0.950249               129        126700   
2             4.000781               2.392521                74         45480   
3             4.206746               1.613522               123         67945   
4             3.319036               1.680629                92         37285   

   pressure_mean25  pressure_var25  total_time25  class  
0      1749.278166     296102.7676        144605      P  
1      1504.768272     278744.2850        298640      P  
2      1431.443492     144411.7055         79025      P  
3      1465.843329     230184.7154        181220      P  
4      1841.702561     158290.0255         72575      P  

[5 rows x 452 columns]

In [3]:
data.columns

Index(['ID', 'air_time1', 'disp_index1', 'gmrt_in_air1', 'gmrt_on_paper1',
       'max_x_extension1', 'max_y_extension1', 'mean_acc_in_air1',
       'mean_acc_on_paper1', 'mean_gmrt1',
       ...
       'mean_jerk_in_air25', 'mean_jerk_on_paper25', 'mean_speed_in_air25',
       'mean_speed_on_paper25', 'num_of_pendown25', 'paper_time25',
       'pressure_mean25', 'pressure_var25', 'total_time25', 'class'],
      dtype='object', length=452)

In [4]:
l = data.columns
len(l)

452

In [5]:
y = data['class']
y = y.to_numpy()
y

array(['P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P',
       'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P',
       'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P',
       'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P',
       'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P',
       'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P',
       'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'H', 'H',
       'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H',
       'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H',
       'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H',
       'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H',
       'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H',
       'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H',
       'H', 'H', 'H', 'H', 'H'], dtype=object)

In [6]:
Y=[]
for i in y:
    if i == 'P':
        Y.append(1)

    else:
        Y.append(0)

In [7]:
import numpy as np
Y = np.array(Y)

In [8]:
Y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
drop = ['ID', 'class']
X = data.drop(columns=drop, axis=1)

In [10]:
X.head()

air_time1  disp_index1  gmrt_in_air1  gmrt_on_paper1  max_x_extension1  \
0       5160     0.000013    120.804174       86.853334               957   
1      51980     0.000016    115.318238       83.448681              1694   
2       2600     0.000010    229.933997      172.761858              2333   
3       2130     0.000010    369.403342      183.193104              1756   
4       2310     0.000007    257.997131      111.275889               987   

   max_y_extension1  mean_acc_in_air1  mean_acc_on_paper1  mean_gmrt1  \
0              6601          0.361800            0.217459  103.828754   
1              6998          0.272513            0.144880   99.383459   
2              5802          0.387020            0.181342  201.347928   
3              8159          0.556879            0.164502  276.298223   
4              4732          0.266077            0.145104  184.636510   

   mean_jerk_in_air1  ...  mean_gmrt25  mean_jerk_in_air25  \
0           0.051836  ...   249.729085            0.141434   
1           0.039827  ...    77.258394            0.049663   
2           0.064220  ...   193.667018            0.178194   
3           0.090408  ...   163.065803            0.113905   
4           0.037528  ...   147.094679            0.121782   

   mean_jerk_on_paper25  mean_speed_in_air25  mean_speed_on_paper25  \
0              0.024471             5.596487               3.184589   
1              0.018368             1.665973               0.950249   
2              0.017174             4.000781               2.392521   
3              0.019860             4.206746               1.613522   
4              0.020872             3.319036               1.680629   

   num_of_pendown25  paper_time25  pressure_mean25  pressure_var25  \
0                71         40120      1749.278166     296102.7676   
1               129        126700      1504.768272     278744.2850   
2                74         45480      1431.443492     144411.7055   
3               123         67945      1465.843329     230184.7154   
4                92         37285      1841.702561     158290.0255   

   total_time25  
0        144605  
1        298640  
2         79025  
3        181220  
4         72575  

[5 rows x 450 columns]

In [11]:
X.to_numpy()

array([[5.16000000e+03, 1.25000000e-05, 1.20804174e+02, ...,
        1.74927817e+03, 2.96102768e+05, 1.44605000e+05],
       [5.19800000e+04, 1.60000000e-05, 1.15318238e+02, ...,
        1.50476827e+03, 2.78744285e+05, 2.98640000e+05],
       [2.60000000e+03, 1.03000000e-05, 2.29933997e+02, ...,
        1.43144349e+03, 1.44411706e+05, 7.90250000e+04],
       ...,
       [3.83000000e+03, 8.36000000e-06, 1.51536989e+02, ...,
        1.91557349e+03, 1.28727124e+05, 8.34450000e+04],
       [1.76000000e+03, 7.96000000e-06, 2.89518195e+02, ...,
        1.91557349e+03, 1.28727124e+05, 8.34450000e+04],
       [2.87500000e+03, 8.18000000e-06, 2.35769350e+02, ...,
        1.91557349e+03, 1.28727124e+05, 8.34450000e+04]])

In [12]:
from sklearn.preprocessing import MinMaxScaler, RobustScaler, StandardScaler
minmax = MinMaxScaler()
minbased = minmax.fit_transform(X)

In [13]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(minbased, Y, test_size=0.15, random_state=42)

In [14]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=100)
rf.fit(X_train, y_train).score(X_test, y_test)

0.8518518518518519

In [15]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train).score(X_test, y_test)

0.7407407407407407

In [16]:
from sklearn.svm import SVC
svm = SVC()
svm.fit(X_train, y_train).score(X_test, y_test)

0.8148148148148148

In [17]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
dt.fit(X_train, y_train).score(X_test, y_test)

0.8888888888888888

In [18]:
from sklearn.ensemble import BaggingClassifier
bag = BaggingClassifier(estimator=KNeighborsClassifier(n_neighbors=3), n_estimators=50)
bag.fit(X_train, y_train).score(X_test, y_test)

0.7407407407407407

In [19]:
bag1 = BaggingClassifier(estimator=DecisionTreeClassifier(), n_estimators=100)
bag1.fit(X_train, y_train).score(X_test, y_test)

0.8888888888888888

In [20]:
#robust

In [21]:
robust = RobustScaler()
Xrob = robust.fit_transform(X)

In [22]:
from sklearn.model_selection import train_test_split

Xtrain, Xtest, ytrain, ytest = train_test_split(Xrob, Y, test_size=0.15, random_state=42)

In [23]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=100)
rf.fit(Xtrain, ytrain).score(Xtest, ytest)

0.8888888888888888

In [24]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, ytrain).score(Xtest, ytest)

0.8148148148148148

In [25]:
from sklearn.svm import SVC
svm = SVC()
svm.fit(Xtrain, ytrain).score(Xtest, ytest)

0.8518518518518519

In [26]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
dt.fit(Xtrain, ytrain).score(Xtest, ytest)

0.8148148148148148

In [27]:
from sklearn.ensemble import BaggingClassifier
bag = BaggingClassifier(estimator=KNeighborsClassifier(n_neighbors=3), n_estimators=50)
bag.fit(Xtrain, ytrain).score(Xtest, ytest)

0.7037037037037037

In [28]:
bag1 = BaggingClassifier(estimator=DecisionTreeClassifier(), n_estimators=100)
bag1.fit(Xtrain, ytrain).score(Xtest, ytest)

0.8518518518518519

In [29]:
bag.predict(Xtest)

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 0])

In [30]:
ytest

array([0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 0])

In [31]:
bag1.predict(Xtest)

array([1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 0])